# Generated by Django 3.2.6 on 2022-02-14 09:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('refill', 'refill'), ('withdraw', 'withdraw'), ('transfer', 'transfer'), ('incoming transfer', 'incoming transfer')], max_length=30, verbose_name='Тип операции')),
                ('details', models.CharField(max_length=255, verbose_name='Детали операции')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата совершения операции')),
                ('sum', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, 'Требуется ввести сумму')], verbose_name='Сумма')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incoming', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfer', to='balance.transaction', verbose_name='Входящий перевод')),
                ('outcoming', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcoming_transfer', to='balance.transaction', verbose_name='Исходящий перевод')),
            ],
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Баланс пользователя')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
