# Generated by Django 3.2.6 on 2022-02-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='operation',
            field=models.CharField(choices=[('refill', 'refill'), ('withdraw', 'withdraw'), ('transfer', 'transfer')], max_length=30, verbose_name='Тип операции'),
        ),
    ]
