# Generated by Django 3.2.7 on 2021-09-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankcontroller', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneycard',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
