# Generated by Django 3.2.7 on 2021-09-09 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankcontroller', '0004_service_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('RUB', 'RUB'), ('EUR', 'EUR'), ('BYN', 'BYN')], default='BYN', max_length=6, verbose_name='Валюта'),
        ),
    ]
