# Generated by Django 3.2.7 on 2021-09-12 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bankcontroller', '0005_alter_service_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('user_received', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='money_recived', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, который получил')),
                ('user_transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='money_transfer', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, который перевел')),
            ],
            options={
                'verbose_name': 'Перевод денежных средств',
                'verbose_name_plural': 'Переводы денежных средств',
            },
        ),
    ]
