# Generated by Django 3.2.7 on 2021-09-12 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bankcontroller', '0006_moneytransfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoLsit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money_transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='info_list', to='bankcontroller.moneytransfer', verbose_name='Трансфер денег')),
                ('shop_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='info_list', to='bankcontroller.shopservice', verbose_name='Покупка услуги')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_list', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'ИНФО',
                'verbose_name_plural': 'ИНФО',
            },
        ),
    ]
