# Generated by Django 3.2.7 on 2021-09-12 17:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bankcontroller', '0007_infolsit'),
    ]

    operations = [
        migrations.AddField(
            model_name='infolsit',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время и дата'),
            preserve_default=False,
        ),
    ]
