# Generated by Django 3.2.7 on 2021-09-13 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankcontroller', '0008_infolsit_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InfoLsit',
        ),
    ]
